version: '3.1'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: updates
    restart: always
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
